### PR TITLE
feat: support database snapshot

### PR DESCRIPTION
**Pull request by olavloite**
Adds support for the `snapshot` command and other commands that rely on database snapshots being supported. It does so by injecting a custom `SnapshotGeneratorFactory` using reflection, as there is no API support for doing this. The injected factory will only execute custom logic if the database is a Cloud Spanner database. For all other databases the original factory will be used.

### CODE REVIEW

**Comment by mescanne** [comment]
I think the biggest concern is what it should look like long term - if we could get a feature request in Liquibase to disable unique constraints (or even just automatically disable them of the table doesn't exist in the information schema) then that would be good.

I'll look again Monday.

**Comment by olavloite** [comment]
> I think the biggest concern is what it should look like long term - if we could get a feature request in Liquibase to disable unique constraints (or even just automatically disable them of the table doesn't exist in the information schema) then that would be good.
> 

If we could have some way of controlling / disabling it through some kind of `supportsUniqueConstraint` method in Liquibase, that would indeed be a lot better than this.

**Review by mescanne — COMMENTED** [review]
> > I think the biggest concern is what it should look like long term - if we could get a feature request in Liquibase to disable unique constraints (or even just automatically disable them of the table doesn't exist in the information schema) then that would be good.
> 
> If we could have some way of controlling / disabling it through some kind of `supportsUniqueConstraint` method in Liquibase, that would indeed be a lot better than this.

Not sure if you got my email -- there is another approach I've found that may be a (bit) less ugly.

**Review by mescanne — APPROVED** [review]

**Comment by olavloite** [comment]
Strange, [CircleCI](https://app.circleci.com/pipelines/github/cloudspannerecosystem/liquibase-spanner/243/workflows/89faab5a-399d-4dbe-ba69-043dda5c9801/jobs/254) reports that the build has long finished successfully, but it can't report it back to GitHub.

**Pull request merged**
