### PR TITLE
fix: escape single quote with backslash

### LINKED ISSUE #94: loadData not escaping single quotes correctly
When using loadData to import a CSV, the changeset fails if there is a string in the CSV that contains a single quote. This is happening because Liquibase attempts to escape the single quote as `''` rather than as `\'`. For example,

```
IntVal,StrVal
1,"This won't work"
```

```
Unexpected error running Liquibase: Migration failed for change set changelog.yaml::load-data-Test::evtilley:
     Reason: liquibase.exception.DatabaseException: INVALID_ARGUMENT: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Syntax error: Expected ")" or "," but got string literal 't work' [at 1:56]
INSERT INTO Test (IntVal, StrVal) VALUES (1, 'This won''t work')
                                                       ^ [Failed SQL: (3) INSERT INTO Test (IntVal, StrVal) VALUES (1, 'This won''t work')]
```

I've attached a full reproduction below.

[liquibase-spanner-escaping-issue.zip](https://github.com/cloudspannerecosystem/liquibase-spanner/files/6624959/liquibase-spanner-escaping-issue.zip)

### PR DESCRIPTION
**Pull request by evtilley**
Currently, this extension uses the Liquibase default behavior of escaping single quotes with `''`. This change overrides that behavior to use `\'` instead.

Fixes #94.

### CODE REVIEW

**Comment by mescanne** [comment]
Evtilley - thanks for this. It looks like the right thing to do, replacing the default JDBC escape method which works differently.

It would be good to add a test for it. I was working with it and our loadData changeset uses usePreparedStatements: true and it handles ' characters just fine. Could you try your test with usePreparedStatements: true?

We should still fix this, but I'd like a test that shows it working. We can duplicate the existing loadData test or create a simpler one based on your test case.

**Comment by evtilley** [comment]
Thanks @mescanne . Using prepared statements will avoid this issue.

I took a shot at writing a unit test, and it turns out that this behavior can't be reproduced using liquibase-core 4.3.1, which this project currently uses. It can be reproduced in 4.3.2, which changes the logic that decides when to use prepared statements (see [this commit](https://github.com/liquibase/liquibase/commit/6e29566026549868ac936d9a7997f1841a42f94a)).

Should I take on the dependency upgrade in this PR?

**Comment by mescanne** [comment]
Go for it. It isn't clear to me the intent behind that commit -- regardless, this is focused on the string escape logic, so if we can get a minimal test for the escape string we'll be good. We can upgrade to 4.3.2 if it helps reproduce it.

**Comment by mescanne** [comment]
Great job! Do you need a release for this? Or just use prepared statements for now, and this will roll into the next release.

**Comment by evtilley** [comment]
Thanks @mescanne! Yes, please create a release.

**Pull request merged**
